import sgslogin

if __name__ == '__main__':
    sgslogin.write_down([
        ('sgsx5q01', 0, 'xiahoujinxuan', True),
        ('2', 1, 'xiaxia'),
        ('3', 1, 'muchanglan'),
        ('4', 1, 'jiangcheng'),
        ('j401', 4, 'yuntianhe'),
        # ('sgsxj401', 0, 'yuntianhe', True),
        ('2', 1, 'hanlingsha'),
        ('3', 1, 'liumengli'),
        ('4', 1, 'murongziying'),
        ('5', 1, 'xuanxiao'),
        ('3w01', 4, 'nangonghuang'),
        ('2', 1, 'wenhui'),
        ('3', 1, 'xingxuan'),
        ('4', 1, 'wangpengxu'),
        ('5', 1, 'leiyuange'),
        ('j501', 4, 'jiangyunfan'),
        ('2', 1, 'tangyurou'),
        # ('sgsxj502', 0, 'tangyurou', True),
        ('3', 1, 'longyou'),
        ('4', 1, 'xiaoman'),
        ('5', 1, 'jiangshili'),
        ('6', 1, 'moyiyi'),
        ('7', 1, 'yanshiqiongbing'),
        ('8', 1, 'ouyanghui'),
        ('301', 3, 'jingtian'),
        ('2', 1, 'tangxuejian'),
        ('3', 1, 'longkui'),
        ('4', 1, 'longkuigui'),
        ('5', 1, 'chonglou'),
        ('6', 1, 'zixuan'),
        ('7', 1, 'xuchangqing'),
        ('201', 3, 'wangxiaohu'),
        ('2', 1, 'sumeimei'),
        ('3', 1, 'shenqishuang'),
        ('4', 1, 'liyiru'),
        ('6', 1, 'konglin'), 
        ('7', 1, 'mozunzun'),
        ('an', 3, 'annunu'),
        ('106', 2, 'jiujianxian'),
        ('7', 1, 'baiyuejiaozhu'),
        ('mjxy', 5, 'lixiaoyao', False),
        ('lr', 2, 'zhaolinger', False),
        ('yr', 2, 'linyueru', False),
        ('bioayu^2sina.cn', 8, 'baiyousb250', False)
    ], sgslogin.run_as_default)
# run_preyonly run_as_default, run_complete, run_once
